"""UMLS Semantic Type (TUI) registry and filtering.

Reads ``data/semantic_types.json`` (generated by
``scripts/build_semantic_types.py`` from official NLM files) and
provides lookup / filtering helpers used by the extractor.

Usage::

    from rag_lib.umls.semantic_types import is_relevant, get_type_name

    if is_relevant("T047"):
        print(get_type_name("T047"))  # "Disease or Syndrome"
"""

from __future__ import annotations

import json
from pathlib import Path

_DATA_PATH = Path(__file__).parent / "data" / "semantic_types.json"

# Lazy-loaded cache
_DATA: dict | None = None


def _load() -> dict:
    global _DATA
    if _DATA is None:
        with open(_DATA_PATH, encoding="utf-8") as fh:
            _DATA = json.load(fh)
    return _DATA


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def is_relevant(tui: str) -> bool:
    """Check whether a TUI belongs to one of the relevant groups."""
    return tui in set(_load()["relevant_tuis"])


def get_type_name(tui: str) -> str | None:
    """Return the human-readable name for a TUI, or None if unknown."""
    entry = _load()["all_types"].get(tui)
    return entry["name"] if entry else None


def get_type_group(tui: str) -> str | None:
    """Return the semantic group code for a TUI, or None if unmapped."""
    entry = _load()["all_types"].get(tui)
    return entry["group"] if entry else None


def relevant_tuis() -> set[str]:
    """Return the set of all TUIs belonging to relevant groups."""
    return set(_load()["relevant_tuis"])


def all_types() -> dict[str, str]:
    """Return {TUI: name} for all 127 semantic types."""
    return {tui: info["name"] for tui, info in _load()["all_types"].items()}


def relevant_types() -> dict[str, str]:
    """Return {TUI: name} for only the relevant semantic types."""
    rel = relevant_tuis()
    return {
        tui: info["name"]
        for tui, info in _load()["all_types"].items()
        if tui in rel
    }
